apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pv-pod
spec:
  containers:
    - name: test-dynamic-pv-container
      image: nginx
      volumeMounts:
        - mounthPath: /test-pd
          name: test-volume
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: my-disk-claim-dynamic

# =========== RUN ==========
# $ kubectl create -f dynamic-pv-pod.yaml
### to validate
# $ kubectl get pod -o wide
### validate by checking into GCP disk in use by column


# ========= TEST CASE =========

# $ kubectl exec dynamic-pv-pod -it /bin/sh
### check the disk inside the pod (mounthPath)
# df -h /test-pd
# create test file
# cd /test-pd
# echo "From first pod" > test1.txt
# exit

### delete the pod
# $ kubectl delete -f dynamic-pv-pod.yaml

### re-create the pod
# $ kubectl create -f dynamic-pv-pod.yaml

### run exec command
# kubectl exec dynamic-pv-pod df /test-pd
# kubectl exec dynamic-pv-pod ls /test-pd/
# kubectl exec dynamic-pv-pod cat /test-pd/test1.txt


# ========= CLEAN UP =========

# kubectl delete -f dynamic-pv-pod.yaml
# kubectl delete -f dynamic-pvc.yaml
# kubectl delete storageclass fast