apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rook-operator
  template:
    metadata:
      labels:
        name: rook-operator
    spec:
      containers:
        - name: rook-operator
          image: quay.io/rook/rook-operator
          env:
            - name: ROOK_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace