apiVersion: v1
kind: Pod
metadata:
	name: pod-secret-volume
spec:
	containers:
		- name: mypod
		  image: redis
      volumeMounts:
        - name: foo
          mounthPath: "/etc/foo"
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: mysecret

### ==================== RUN ==============

# $ kubectl create -f pod-secret-volume.yaml

### to validate
# $ kubectl get pod

### to validate inside pod
# $ kubectl exec mypod ls /etc/foo
# $ kubectl execl mypod ls /etc/foo/password
# $ kubectl execl mypod ls /etc/foo/username