apiVersion: v1
kind: Pod
metadata:
	name: pod-secret-env
spec:
	containers:
		- name: mycontainer
		  image: redis
      env:
        - name: SECRET_USERNAME # env variable name
          valueFrom:
            secretKeyRef:
              name: mysecret # name of secrets object
              key: username # key on secrets object
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Never

### ==================== RUN ==============

# $ kubectl create -f pod-secret-env.yaml

### to validate
# $ kubectl get pod

### to validate inside pod
# $ kubectl exec pod-secret-env | grep SECRET