apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4= # encrypted value of admin using base64
  password: MWYyZDFlMmU2N2Rm # encrypted value of 1f2d1e2e67df using base64



### before we create the secrets manually we encrypt the data first using base64
# $ echo -n 'admin' | base64
# the result is YWRtaW4=
# $ echo -n '1f2d1e2e67df' | base64
# the result is MWYyZDFlMmU2N2Rm

### create the secrets object
# $ kubectl create -f secrets.yaml
### to validate
# $ kubectl get secrets
# $ kubectl get secrets mysecret -o yaml

### try to decode the secret

# $ echo -n 'YWRtaW4=' | base64 --decode
# the result is admin
# $ echo -n 'MWYyZDFlMmU2N2Rm' | base64 --decode
# the result is 1f2d1e2e67df