apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
